### ISSUE TITLE
pkg/contents/code/script.js file is missing

### ISSUE THREAD

**Issue by wallace11** [esjeon/krohnkite#1]
Trying to run `make` (with any option) will result in an error:
`make: *** [Makefile:44: pkg/contents/code/script.js] Error 127`

Checking the source code, I can't find that file anywhere. Maybe forgot to add it to the repo?

**Comment by esjeon** [comment]
Hmm, would you check the version of `tsc` you are using? Makefile uses `--outFile` flag of `tsc`, but the flag is available only after 1.8 or something.

**Comment by esjeon** [comment]
Happens. Thanks for checking out.
