### ISSUE TITLE
how set Rounded Corners in this？

### ISSUE THREAD

**Issue by Arzelan** [esjeon/krohnkite#109]
Tiling + Rounded Corners + Gaps in KDE?   in your YouTube。   what can i set Rounded Corners with krohnkite。thankyou

**Comment by esjeon** [comment]
This is outside of what Krohnkite does.

Simple googling gave me [this](https://github.com/alex47/KDE-Rounded-Corners), but I'm not aware of the specifics. You may want to check communities like [r/KDE](https://www.reddit.com/r/kde/) instead.
