### ISSUE TITLE
Wayland

### ISSUE THREAD

**Issue by alexjp** [esjeon/krohnkite#11]
Just a heads up:

I am using opensuse git kde with wayland. It seems with native wayland apps, windows don't tile at all.

I can see that if I do GDK_BACKEND=x11 and QT_QPA_PLATFORM=xcb, windows get tilled, but with GDK_BACKEND=wayland and QT_QPA_PLATFORM=wayland, they do not.

I don't think kde wayland is ready yet, so no big deal, but maybe something to look into the future ?

Thanks for your awesome work !

**Comment by esjeon** [comment]
It's a KWin upstream issue. KWin currently doesn't expose Wayland clients through it's API.
