### ISSUE TITLE
'Move left' and 'move right' do nothing

### ISSUE THREAD

**Issue by Seon82** [esjeon/krohnkite#119]
**Symptom**
The 'move left' and 'move right' hotkeys don't seem to do anything after having spawned two windows left/right of each other.

**How to Reproduce**

1. Launch any two windows
2. Press key-combo related to either move left or move right
3. Nothing happens

**Expected behavior**

The windows to move left and right :)

**Environment**
 - Distro: Manjaro 20.1.2
 - KWin version: 5.19.5-2
 - Krohnkite version: 0.7
 - List of KWin scripts in use: Nothing else

**Notes**
Moving up/down works fine. Restarting a few times didn't help.

Keep up the good work, this script is really nice!

**Comment by esjeon** [comment]
I think what you want is setting the key behavior to "Directional" in the script settings. The default behavior is set to "DWM style" currently, which doesn't support moving windows left-right.

You can find how to enable the script settings dialog in the [README](https://github.com/esjeon/krohnkite/#enabling-user-configuration).

**Comment by Seon82** [comment]
That was it - I'd tried changing this setting previously, but hadn't thought to restart after that to apply the changes. My bad.

Thank you very much for the quick reply and help !
