### ISSUE TITLE
window borders are not working

### ISSUE THREAD

**Issue by vedang-jammy** [esjeon/krohnkite#129]
**Symptom**
No window borders are showing even though I have set them using,
kwriteconfig5 --file ~/.config/kdeglobals --group WM --key frame 153,102,255
 kwriteconfig5 --file ~/.config/kdeglobals --group WM --key inactiveFrame  239,240,241
I have tried different color values but it isn't working
Also, I have enabled borders in breeze theme
**Expected behavior**
To show borders around the windows

**Environment**
 - Distro: Garuda linux
 - KWin version: 
 - Krohnkite version: 0.8
 - List of KWin scripts in use: 

**Notes**
Anything that you want to tell developers about.

**Comment by esjeon** [comment]
Those commands are for setting the colors of window border, so, if borders are enabled, you should be already seeing the borders.

Make sure that the border size is set to, at least, "no side borders" in `Window Decorations`, and that there are no Window/Decoration rules that remove borders.

**Comment by vedang-jammy** [comment]
I have set the border to 'normal'(I tried setting them to different sizes but it didn't work) and there is no rule for removing the borders.

**Comment by silviubogan** [comment]
+1. I have the same issue as @vedang-jammy.

**Comment by neondeex** [comment]
@silviubogan did you get how to fix it?

**Comment by vedang-jammy** [comment]
Not using kde anymore.

**Comment by silviubogan** [comment]
> @silviubogan did you get how to fix it?

No, I did not get how to fix it. Sorry.

**Comment by PavlySz** [comment]
Did anybody find a fix for that bug?

**Comment by p1k0pan** [comment]
I wanna ask too.

> Did anybody find a fix for that bug?

**Comment by amirhaouala** [comment]
Install One dark Aurorae in Get New Windows Decorations ( I prefer the green variation with Garuda and krohnkite )

**Comment by PavlySz** [comment]
> Install One dark Aurorae in Get New Windows Decorations ( I prefer the green variation with Garuda and krohnkite )

Yeah, that's an easy workaround, but I'd like more control over the border colours. Will keep searching and update you if I find anything.

**Comment by dekiesel** [comment]
May I ask why this has been closed? I am having the same issue on Ubuntu 21.10, kde 5.24.2. The border size is set to large.

**Comment by mushi-nova** [comment]
This same issue or bug persists for me as well.

**Comment by sricks** [comment]
I'm not a krohnkite user, but I had this problem with Kwin generally because my compositor was disabled. No borders appear until compositor is turned back on.
