### ISSUE TITLE
Master Window is always on the left.

### ISSUE THREAD

**Issue by ben2talk** [esjeon/krohnkite#145]
I would like the option with (Quarter, Tile, spiral) to switch the 'master' side.
Is this an easy task? I can't find a way to do it.

**Comment by miguelcaravantes** [comment]
you can use the rotate function, default is meta + r, as far as I remember or you cant set a custom in kwin shortcuts krohnkite rotate

**Comment by ben2talk** [comment]
Thank You so much, I confused switching with rotating. Feeling a little stupid now... Let's close this quickly!
