### ISSUE TITLE
Inacticve and Active frames not working in plasma 5.2

### ISSUE THREAD

**Issue by andypaling** [esjeon/krohnkite#148]
**Symptom**
Frame colors not working with the new plasma update

**How to Reproduce**
setup the colored window borders as guided in the readme for this repo.

**Expected behavior**
I had mine setup in the previous version of plasma with a red frame for the active window and a grey frame for the inactive window and red for the active window and all was working perfectly. However now, all the borders are grey.

**Environment**
 - Distro: Arch 
 - KWin version: 5.21
 - Krohnkite version: 0.8
 - Only krohnkite

**Comment by r0skar** [comment]
I can confirm this issue (same system specs). One thing I noticed that seems related: when switching to Oxygen window decorations, the active/inactive shadow works after the window has been resized one :man_shrugging:

**Comment by andypaling** [comment]
@r0skar I have found the fix to this thanks to someone replying to a reddit post I made about it. I you go into appearance -> Colors than change your color scheme to any random one and apply then back to what you were using before, this should fix the issue. I worked for me and the person who told me about it.

**Comment by m4rkv5** [comment]
@andypaling Thanks for the hint. I got my border colors working when I switched to breeze dark high contrast. When i switch back to breeze dark they dissapear again.

**Comment by andypaling** [comment]
@m4rkv5 Yeah its strange, my colored window borders have been quite buggy since the kde update.

**Comment by m4rkv5** [comment]
@andypaling I made a gif https://i.imgur.com/VJJCUJX.gifv
Breeze and Breeze dark high contrast working
Breeze white and breeze dark not working

**Comment by m4rkv5** [comment]
Found the issue in /usr/share/color-schemes/BreezeDark.colors
These Blocks are only in the not working color shemes. I deleted them and now it works.
[Colors:Header]
BackgroundAlternate=42,46,50
BackgroundNormal=49,54,59
DecorationFocus=61,174,233
DecorationHover=61,174,233
ForegroundActive=61,174,233
ForegroundInactive=161,169,177
ForegroundLink=29,153,243
ForegroundNegative=218,68,83
ForegroundNeutral=246,116,0
ForegroundNormal=252,252,252
ForegroundPositive=39,174,96
ForegroundVisited=155,89,182

[Colors:Header][Inactive]
BackgroundAlternate=49,54,59
BackgroundNormal=42,46,50
DecorationFocus=61,174,233
DecorationHover=61,174,233
ForegroundActive=61,174,233
ForegroundInactive=161,169,177
ForegroundLink=29,153,243
ForegroundNegative=218,68,83
ForegroundNeutral=246,116,0
ForegroundNormal=252,252,252
ForegroundPositive=39,174,96
ForegroundVisited=155,89,182

**Comment by ivangjxyz** [comment]
How do you know that will not break something else?

**Comment by m4rkv5** [comment]
Deleted config values should load default values.

**Comment by thingsiplay** [comment]
> Found the issue in /usr/share/color-schemes/BreezeDark.colors These Blocks are only in the not working color shemes. I deleted them and now it works. [Colors:Header] BackgroundAlternate=42,46,50 BackgroundNormal=49,54,59 DecorationFocus=61,174,233 DecorationHover=61,174,233 ForegroundActive=61,174,233 ForegroundInactive=161,169,177 ForegroundLink=29,153,243 ForegroundNegative=218,68,83 ForegroundNeutral=246,116,0 ForegroundNormal=252,252,252 ForegroundPositive=39,174,96 ForegroundVisited=155,89,182
> 
> [Colors:Header][Inactive] BackgroundAlternate=49,54,59 BackgroundNormal=42,46,50 DecorationFocus=61,174,233 DecorationHover=61,174,233 ForegroundActive=61,174,233 ForegroundInactive=161,169,177 ForegroundLink=29,153,243 ForegroundNegative=218,68,83 ForegroundNeutral=246,116,0 ForegroundNormal=252,252,252 ForegroundPositive=39,174,96 ForegroundVisited=155,89,182

Hi, I'm from the future. Just wanted to say "Thank You". Just recently Krohnkite got support for Wayland on KDE 6, so I tried it again. The active window border drove me crazy as it did not work after the instructions on the README. After deleting those lines the borders appear! Thank you.

However I want to add or suggest not to change anything from "/usr/share/color-schemes/BreezeDark.colors". Those lines weren't even found in the file. Instead edit "~/.config/kdeglobals" in your personal configuration. Those lines were found in it too.
