### ISSUE TITLE
Separate layouts per desktop/activity

### ISSUE THREAD

**Issue by Teyras** [esjeon/krohnkite#15]
I often have my windows arranged in a specific layout (e.g. different width of the master window) on each virtual desktop/activity. Is it be possible to keep a separate layout for those?

**Comment by esjeon** [comment]
Done. (af21bb8b9689ffa2c0bf2d834e2e22f5d3c775d1 and b936cfa4341876fe80cb195b2a3b11af68dba355)

I already tested it, but will keep this ticket open for a few days.

**Comment by Teyras** [comment]
Awesome, thank you! Alas, after I updated, I cannot find the checkboxes that enable this feature, even after a reboot. Is there anything I have to do for the KCM to refresh?

**Comment by esjeon** [comment]
Okay, I think it's safe to close now.
