### ISSUE TITLE
Windows freeze on startup

### ISSUE THREAD

**Issue by waphire** [esjeon/krohnkite#16]
Hello! 

I've been using Krohnkite for a few days and while the functionality is good, the windows freeze / go unresponsive in the following cases:
- startup is frozen
- changing virtual desktops (workspaces) 
- opening another program causes the previous one to freeze
- changing focus from one to the other causes the previous one to freeze

I do have the jiggle option set but it takes multiple to-and-fro(s) for the window to unfreeze.

**Comment by esjeon** [comment]
Hmm, the only thing that crosses my mind is that there can be more than one instances of Krohnkite running. KWin currently cannot clear up all event listeners upon disabling scripts, which results in race condition b/w instances. This, by 100% chance, freezes every window within a few second.

Would you try again after restarting KWin? Re-login or `kwin_x11 --replace` on a terminal should work.

**Comment by esjeon** [comment]
Commit 5caa4e0 will disconnect all signals when the script is disabled.

**Comment by waphire** [comment]
Tried replacing, logging out and in and restarting. Uninstalled and reinstalled the script with the latest commit. However, the same behaviour persists. Should I make a gif showcasing what I mean?

**Comment by esjeon** [comment]
Hmmmm, that's quite strange. I think GIF isn't necessary yet, since freezing does happen in other cases too.

Would you let me know the following information:
1. Distro
2. KWin version (`kwin_x11 --version`)
3. List of installed KWin scripts (a full screenshot of `KWin Scripts` dialog would suffice)

FYI, I'm developing/using this script on Arch, and test it on KDE Neon (based on Ubuntu 18.04 LTS).

**Comment by waphire** [comment]
1 & 2: ![screenshot_20181217_134831](https://user-images.githubusercontent.com/30401343/50074719-aa197380-01d4-11e9-8212-54f16bc08d5e.png)

3: ![screenshot_20181217_134756](https://user-images.githubusercontent.com/30401343/50074737-b998bc80-01d4-11e9-9b72-de27035a4218.png)

**Comment by esjeon** [comment]
Up-to-date Arch, KWin 5.14.4, w/ Kvantum. I think your setup is overall the same as mine. It can be a hardware-specific (upstream) issue, or I can't think of any other places to look into.

I attached a debug-enabled version of the master branch. Would you try again with it?

To see the debug message, you have to restart KWin in a terminal (`kwin_x11 --replace 2>&1 | tee -a ~/kwin.log`). With an output dump, maybe I can figure out what's going on.

[krohnkite-0.2.kwinscript.zip](https://github.com/esjeon/krohnkite/files/2687519/krohnkite-0.2.kwinscript.zip)

**Comment by esjeon** [comment]
Ah, okay. Now I see. There's a race condition where multiple invocations of re-arrangement collide with each other. I think this is the source of the problem.

One thing to note is that KWin script runs multiple *jobs* concurrently, unlike single-threaded Javascript. Active jobs often preempted by newer jobs, and, in this case, current re-arrangement job is preempted by new request for re-arrangement. What makes it worse is that these jobs preempt each other and resizing operation gets completely interleaved. The end result is completely unpredictable.

Simple flagging can prevent the race condition itself, but it can cause some timing issues like missing rearrangement requests.

**Comment by esjeon** [comment]
I've just pushed a quick fix(b5cc33e) to master. I hope this solves your problem.

**Comment by waphire** [comment]
`make uninstall && reboot` 
`make install && reboot` 

No difference. :(

Here's another debug log
[kwin.log](https://github.com/esjeon/krohnkite/files/2693422/kwin.log).

**Comment by esjeon** [comment]
'kay, sorry for bailing out for a while. I've been working on this issue behind the scene.

Commit 75e4151 unfreezes some applications that resizes themselves, like Firefox (and its variants) and many (or most) KDE applications that remembers last window position. I seriously hope this does fix this, even partially, or I'm gonna ragequit. lol

**Comment by waphire** [comment]
Hey, man, amazing work. No, really. Amazing work! 

Although I'm testing on a different machine right now (used to have KDE on my laptop, now on PC), I experience no freezing whatsoever. Thank you and Merry Christmas!
