### ISSUE TITLE
question: when i move windows by dragging title, it becomes float. How do i make it tile again?

### ISSUE THREAD

**Issue by tuananh** [esjeon/krohnkite#161]
when i move windows by dragging title, it becomes float. How do i make it tile again?

**Comment by andrei-pavel** [comment]
Set the `Khrohnkite: Float All` in shortcuts. For me, it's `Meta + Shift + F`. Not sure if it's the default. I may have changed it. Despite the name of `Float All`, it cycles between floating and tiling all windows. So you press it a maximum of two times and you have all the windows tiled.

**Comment by tuananh** [comment]
@andrei-pavel that's exactly what i'm looking for. thanks.
