### ISSUE TITLE
Dragging tab out of chrome strobes the window

### ISSUE THREAD

**Issue by reubenfirmin** [esjeon/krohnkite#185]
In chrome, you can drag a tab out to create a new window. This confuses Krohnkite;  it starts strobing between the two windows, and doesn't allow the tab to be dropped back into the chrome window.

**Comment by ilkerhk** [comment]
I experience this everyday and it is very annoying especially when you try to put a window into another window as a tab. This does not happen in Firefox (only happening in Chrome).
