### ISSUE TITLE
Ghost Windows on minimize

### ISSUE THREAD

**Issue by zany130** [esjeon/krohnkite#186]
**Symptom**
Window contents are being left behind on minimize/close of the window

**How to Reproduce**
1. tile multiple applications
2. minimize, close, move them around, and make some float
3. Some of those windows will be left behind even after close/minimize and will tile with the rest of your windows

**Expected behavior**
No ghost windows. Minimize closing windows does not leave behind contents

**Environment**
 - Distro: Garuda Linux
 - KWin version: 5.22
 - Krohnkite version:  r464.2a47753-2 AUR
 - List of KWin scripts in use: Activate Latte Launcher Menu, Force Blur, Latte Window Colors, Shake
**Notes**
Anything that you want to tell developers about.
My applications are NOT supposed to be transparent unless there out of focus so that's another indicator that this bug happened for me. Also that vivaldi window is not really running its just leftover from the previous instance so a "ghost window"
![Screenshot_7](https://user-images.githubusercontent.com/25832539/132955625-3b2a6b19-7fdd-47da-89bd-1ba4325a444f.png)

**Comment by v3ss0n** [comment]
I think it has to be done with forced blur , have you test without krohnkite ?

**Comment by zany130** [comment]
not sure could be something I tried is resetting all my kde configs and not enabling the transparency effect on inactive windows hasn't happen to me again yet. I did try without kronkite for a while (before resting the configs) and it would still happen so yeah might not even be krohnkite sorry about that.
