### ISSUE TITLE
Make install fails wiht compile error

### ISSUE THREAD

**Issue by phiroict** [esjeon/krohnkite#197]
**Symptom**
Compile error when running the make install script 

**How to Reproduce**

After downloading the git repo with 
```
git clone git@github.com:esjeon/krohnkite.git
```
and then 
```
cd krohnkite && make install 
```
It fails with 

```
> make install             
tsc
src/driver/kwin/kwindriver.ts:227:53 - error TS2571: Object is of type 'unknown'.

227             debug(() => "Error raised from line " + e.lineNumber);
                                                        ~


Found 1 error.

make: *** [Makefile:71: krohnkite.js] Error 2

```

**Expected behavior**
Installation of the krohnkite extension. 

**Environment**
 - Distro: Arcolinux [Linux philip-precision7740 5.16.4-arch1-1 #1 SMP PREEMPT Sat, 29 Jan 2022 19:08:13 +0000 x86_64 GNU/Linux
]
 - KWin version: [KDE Plasma: 5.23.5, KDE Frameworks: 5.90.0, Qt Version 5.15.2]
 - Krohnkite version: [git main HEAD - 2a47753fa2a37a9035116df4a7c2d73044373d82]
 - List of KWin scripts in use: [e.g. MinimizeAll, VideoWall, Synchronize skip switcher with taskbar]
 - Node version [17.3.0]
 - Typescript version [4.5.5]

**Notes**
This is an unmodified Arco KDE installation, en_NZ encoding and locale.

**Comment by EvgeniyMedyankin** [comment]
From aur the same

**Comment by esjeon** [comment]
This should fix the error: https://github.com/esjeon/krohnkite/commit/56f095121c0fdd4b049ba23cb0aea056c8f8e890
