### ISSUE TITLE
I cant' open settings

### ISSUE THREAD

**Issue by ourainbows** [esjeon/krohnkite#198]
I installed kronhnkite recently and I follow the commands to enable user-configuration but when i click the settings i get the error:

`Plugin does not provide configuration file in expected location`

**Environment**
 - Distro: Garuda Linux
 - KWin version: [5.24.0
 - Krohnkite version: 0.8
 - List of KWin scripts in use: Latte Window Colors

**Comment by esjeon** [comment]
Yup, I have the same issue in another script. https://github.com/esjeon/kwin-forceblur/issues/23#issuecomment-1037872680

It's because the scripts were relying on a deprecated behavior of KWin.

**Comment by esjeon** [comment]
Released the fix to v0.8.1.

**Comment by shipaviu** [comment]
Cannot open Kröhnkite-Settings:

Distro: Fedora 36 Plasma
KWin: 5.24.5
Krohnkite version: 0.8.2

no other Kwin scripts active
