### ISSUE TITLE
EXCEPTIONS

### ISSUE THREAD

**Issue by RaitaroH** [esjeon/krohnkite#2]
Ok... so you really need to exclude stuff like yakuake, conky and alike. Those need to be floating. Same goes for small windows that should not be tiled such as about pages, dialogs and such.

**Comment by esjeon** [comment]
Yes, this is really a necessity. I'll prioritize implementing rule-based filtering.

**Comment by esjeon** [comment]
This is addressed by commit 92b0cb4c53b9ce8cde29f0c236e36ed0542a6488
