### ISSUE TITLE
Tile layout focus shift

### ISSUE THREAD

**Issue by seqizz** [esjeon/krohnkite#20]
Hi and thanks for this extension, working really solid compared to others.

I'd like to ask if there is a way to switch between windows on tile layout, other than alt-tab. It'd be great if customizable shortcuts for "Focus left"/"Focus down" etc.
Not sure if possible, but one can be a lot faster if he/she can set similar meta-shortcuts and travel between windows selectively (like tmux pane navigation).

**Comment by aerosol** [comment]
@seqizz I believe those are provided by plasma:

![image](https://user-images.githubusercontent.com/173738/50799843-1d973800-12de-11e9-9f0b-c57c7aee76ce.png)

**Comment by seqizz** [comment]
Hooly moly, thanks @aerosol I totally missed that. Closing.
