### ISSUE TITLE
in v. 0.8.1 config button no longer visible after update

### ISSUE THREAD

**Issue by dennisMe2** [esjeon/krohnkite#200]
**Symptom**
after update to version 0.8.1 config button is gone. Deselecting, clicking apply and re selecting krohnkite does not restore it. The symlink mentioned in the docs is present and has user / default user group permissions. Krohnkite itself still works.
Removing the script, deleting the symlink and restoring the script does not work, even manually removing and re creating the symlink does not work, the link points to a valid target.

**How to Reproduce**
I use Kubuntu and installed the update via the regular update manager.

**Expected behavior**
The config button should not have disappeared and should have at least re-appeared after disabling / enabling the script.

**Environment**
 - Distro: Kubuntu 21.10
 - KWin version: Plasma 5.22.5
 - Krohnkite version: 0.8.1
 - No other kwin scripts enabled

**Notes**
The script is really handy, thanks a lot for putting in the effort!

**Comment by FredNov** [comment]
confirm. No settings button anymore

Environment

- Distro: MXLinux  x86_64
- KWin version: Plasma 5.20.5
- Krohnkite version: 0.8.1

**Comment by GandertM** [comment]
Confirmed. No settings button anymore

Environment

-     Distro: Manjaro KDE
-     KWin version: Plasma 5.23.5
-     Krohnkite version: 0.8.1

**Comment by esjeon** [comment]
FYI, I'm on 5.24.0 and the script works only with v0.8.1. It seems like KWin changed the behavior abruptly.

From a related bug ticket on the KDE side: https://bugs.kde.org/show_bug.cgi?id=444378 .

> Putting `X-KDE-ConfigModule=kwin/effects/configs/kcm_kwin4_genericscripted` in `metadata.desktop` indeed solves the problem for Plasma 5.24.0. However, I then get the “Plugin does not provide configuration file in expected location” error message on Plasma 5.23.5 when clicking the config button

Hmm, I think I'll just revert the version back to 0.8, and release 0.8.1 separately.

**Comment by dennisMe2** [comment]
Is there no way of sniffing out the plasma version from code?

**Comment by esjeon** [comment]
> Is there no way of sniffing out the plasma version from code?

No unfortunately. It's actually worse, because this is a **_metadata_** issue, which happens far before any of the code can get executed. 🥲

**Comment by esjeon** [comment]
I just reverted the latest change to the metadata: 5bb950eebf70e84c6f86076b2c826b0622ed85f0.

It seems like KWin also made a new release, which added back the support for the legacy behavior.
