### ISSUE TITLE
Any way to keep title bar for floating windows?

### ISSUE THREAD

**Issue by drone1** [esjeon/krohnkite#206]
Otherwise there is no way to move them with the mouse. (I've followed the instructions for removing title bars generally). I'm guessing no, and that the only way to move floating windows w/ the mouse is to keep title bars enabled generally.

Lovely script btw! Loving it!

**Comment by clydebottoms** [comment]
> the only way to move floating windows w/ the mouse is to keep title bars enabled generally.

Hold super then left click to move windows or right click to resize

**Comment by drone1** [comment]
Yep, I figured this out but forgot to close. Thanks.
