### ISSUE TITLE
tdrop windows not being tiled just as yakuake although added to "ignored windows"

### ISSUE THREAD

**Issue by Schweber** [esjeon/krohnkite#209]
**Symptom**
I would like to have a drop-down functionality for some windows with tdrop. E.g. i want `tdrop -am -w 100% -h 100% alacritty` to cover the whole screen like yakuake does.

However, the window is always tiled like any other window although i added `tdrop alacritty,tdrop,alacritty` to `Ignore Windows By Class` and `Ignore Windows By Role` in Krohnkite settings.

**How to Reproduce**
1. add `Ignore Window Rules`
<img width="351" alt="image" src="https://user-images.githubusercontent.com/64630479/196765257-fe0724a7-deb1-4e89-a95c-f497244e91eb.png">
2. launch `tdrop -am -w 100% -h 100% alacritty`
3. the new window is tiled by krohnkite 

**Expected behavior**
The new window occupies full screen like yakuake and gains focus.

**Environment**
 - Distro: NixOS 22.05
 - KWin version: 5.24.5
 - Krohnkite version: 0.8.2
 - List of KWin scripts in use: Always Open on Primary Screen, Krohnkite

**Notes
I can add a Window Rule to force the window type to be `On Screen Display` to drop down fullscreen. But the window doesn't have focus then and i can't have it forced on it.

<img width="746" alt="image" src="https://user-images.githubusercontent.com/64630479/196772376-f7c3ad5d-ba57-42c9-a18b-e8996f8f92cc.png">

If i run `tdrop -Aam -w 100% -h 100% alacritty` the window gains focus but only after running it twice. So this is not a good solution.

I just don't understand why adding alacritty to `Ignored Windows` in Krohnkite isn't working.

**Comment by greatluke** [comment]
Just want to let you know that it works on bismuth
