### ISSUE TITLE
Window placement options

### ISSUE THREAD

**Issue by seqizz** [esjeon/krohnkite#21]
I know this is a hard one, but having a window-specific setting like this:

![like this](https://user-images.githubusercontent.com/307899/50823763-03d50f80-1335-11e9-9a5c-6ffe4c46c9a0.png)

would be great. This way one can setup rules like "if the window class is konsole, width should be %50 of the screen" and/or "set it to master automatically" kind of setups which has endless possibilities.

Again, thanks for the extension.

**Comment by esjeon** [comment]
AFAIK, KWin scripts currently cannot have logic inside settings dialog. Scripts can only use static `*.ui` files, not dynamic QML files. There are not so many options, but, yeah, if I try really hard, there's a way (something like external DBus object), but I won't go down that path for now.

**Comment by seqizz** [comment]
Thanks. Btw it was just a suggestion for easier configuration, I am potato on kwin topic. It does not have to include dynamic stuff, but e.g. having a configuration file support would cut it. Logically there is not much separating this from the current configuration which we can list which types we can float (as a configuration element).

**Comment by esjeon** [comment]
> having a configuration file support would cut it

That sounds like a doable approach. My initial search suggests that QML provides [XHR](http://doc.qt.io/qt-5/qtqml-javascript-qmlglobalobject.html#xmlhttprequest), which [can be used to load files.](https://rschroll.github.io/beru/2013/08/12/opening-a-file-in-qml.html). That really is something.

I'll try working on this, but it will take quite some time. Designing this can be tricky.
