### ISSUE TITLE
Plasma 6.1 Edit Mode

### ISSUE THREAD

**Issue by snoweuph** [esjeon/krohnkite#220]
**Symptom**
When In Edit mode, the Windows from the Different Plasma Modules, which normally just float near their Icon, get Scaled to the full screen
![image](https://github.com/esjeon/krohnkite/assets/76737863/3a6386f8-bb7d-4d94-b01f-bb5e4b1e6770)

**How to Reproduce**
1. Enter Edit Mode
2. Click Panel to Edit it
3. Hover over a Panel Module
4. See that the Hover Window Gets Scaled to Full Screen

**Expected behavior**
There shouldn't be Any Tiling in the new Edit Mode, because its a Specifically Designed Mode, and it destroys its experience

**Environment**
 - Distro: Bazzite 40.30340621.0
 - KWin version: 6.1.0
 - Krohnkite version: 0.9.5 (#dd35653)
 - List of KWin scripts in use:  Krohnkite

**Notes**
I cant use XProp to find out the Window Classes in Edit Mode, so there is no easy way for me to add it to the Block list.
I would say though, that there's nothing to do in edit mode for Krohnkite, so I suggest (if Possible) to disable it inside the Edit Mode

**Comment by sr-tream** [comment]
Workaround: add `plasmashell` into **Ignore Windows**

![image](https://github.com/esjeon/krohnkite/assets/12231048/dd315c44-877d-4f29-b1f0-7b674bffc5d0)

**Comment by snoweuph** [comment]
> Workaround: add `plasmashell` into **Ignore Windows**
> 
> ![image](https://private-user-images.githubusercontent.com/12231048/342541496-dd315c44-877d-4f29-b1f0-7b674bffc5d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMDg4MDEsIm5iZiI6MTcxOTMwODUwMSwicGF0aCI6Ii8xMjIzMTA0OC8zNDI1NDE0OTYtZGQzMTVjNDQtODc3ZC00ZjI5LWIxZjAtN2I2NzRiZmZjNWQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA5NDE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyZDRjMzY2NmRlODk4YzA0MTFmZjdhYmJkY2I3YTZhODdlZGU2NWJiOTJlMDI2ZTA0ODJhNmNjMTZjNmZiOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OHaU2zxZRzRfUnU-QISqol77TvHFA4qLep9aVNCtruE)

yea, a workaround, but how would a user find out the name? becuase using xargs, is defenitly not working. this should defenitly be added as a default

**Comment by sr-tream** [comment]
> > Workaround: add `plasmashell` into **Ignore Windows**
> > ![image](https://private-user-images.githubusercontent.com/12231048/342541496-dd315c44-877d-4f29-b1f0-7b674bffc5d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMDg4MDEsIm5iZiI6MTcxOTMwODUwMSwicGF0aCI6Ii8xMjIzMTA0OC8zNDI1NDE0OTYtZGQzMTVjNDQtODc3ZC00ZjI5LWIxZjAtN2I2NzRiZmZjNWQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA5NDE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyZDRjMzY2NmRlODk4YzA0MTFmZjdhYmJkY2I3YTZhODdlZGU2NWJiOTJlMDI2ZTA0ODJhNmNjMTZjNmZiOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OHaU2zxZRzRfUnU-QISqol77TvHFA4qLep9aVNCtruE)
> 
> yea, a workaround, but how would a user find out the name? becuase using xargs, is defenitly not working. this should defenitly be added as a default

You can view list of all windows with properties in debug console: `qdbus org.kde.KWin /KWin org.kde.KWin.showDebugConsole`

**Comment by Raposa-Coltran** [comment]
perhaps plasmashell should be in the list of ignored windows by default? since this is a *very* standard way to interact with a plasma desktop that is broken as a default, if the workaround has no downsides, shouldnt it just be default behaviour?

**Comment by snoweuph** [comment]
I just recently did na OS reinstall and installed Krohnkite, and its seems to be default now, and works as exsepcted
