### ISSUE TITLE
Ignore Screens/Activities

### ISSUE THREAD

**Issue by DonHugo69** [esjeon/krohnkite#23]
Thank you very much for your work and this nice extension!

I would like to ask if it would be possible to have an option to ignore certain screens and/or certain activities? 

And maybe also to use (parts) of the window title caption to decide if a window should be ignored and/or by the name of the executable?

For reference, I have seen and used these features in the [quarter-tiling-extension](https://github.com/Jazqa/kwin-quarter-tiling). 
![grafik](https://user-images.githubusercontent.com/10484857/51896182-26929b00-23ac-11e9-9252-03b8609f7ce5.png)

**Comment by esjeon** [comment]
I'll work on following features:
1. Skip tiling in activities (by activity name)
2. Skip tiling on screens (by screen number)
3. Ignoring windows by title(caption)
    * w/ simple substring matching. Regex will be an overkill here.

I'll not work on this:
> ignored and/or by the name of the executable?

 AFAIK, this is _impossible_ since neither X11 nor KWin expose such information.

**Comment by DonHugo69** [comment]
@esjeon Thank you very much for your time and effort!

**Comment by esjeon** [comment]
Okay, the adventure was longer and tougher than I originally envisioned.

The feature suggested here are all implemented and usable. But they are not 100% streamlined with the rest of the script yet. It's more of housekeeping from this point.

**Comment by DonHugo69** [comment]
Just tried the new settings and it works as expected!
Thank you very much!

**Comment by esjeon** [comment]
93fb4c189cef556a3238f18c43de08baef137318 defines "Floating" layout, where all windows simply float. "Ignored" activity/screen will internally use this Floating layout, and moving windows in and out of these regions will not disturb other parts of the script. This marks the end of this ticket.
