### ISSUE TITLE
Resizing doesn't check for other windows' geometry restrictions.

### ISSUE THREAD

**Issue by hjri** [esjeon/krohnkite#25]
**Symptom**
You can squeeze other window beyond their intended limits by resizing other windows

**How to Reproduce**
1. Have two windows on screen in tiling mode: Cantata and System settings
2. Try to make System settings window very-very narrow.
3. It resizes to its minimum size but not the size you wanted
4. Try to make Cantata window extra thicc.
5. Cantata now occupies a lot of screen space, System settings window is very narrow.

**Expected behavior**
I think it should be configurable to either:
* Always ignore windows' geometry restrictions
* Always honour windows' geometry restrictions even when resizing other windows.

There could be conflicts when you have several windows that's impossible to fit on the screen given their restrictions, for such cases there should be options of resolution:

* Honour active window size, force-resize others
* Don't resize windows at all, treat them as if the are resized

**Environment**
 - Distro: Debian Testing/Unstable/Experimental
 - KWin version: 5.14.5
 - Krohnkite version: 7c0a8637f1aa9f46d329c4f0e857d0df4630ae98
 - List of KWin scripts in use: Krohnkite

**Notes**
~~Anything that you want to tell developers about.~~

**Comment by esjeon** [comment]
Thanks for reporting the issue.

This is basically a regression. I realized that I accidentally removed the code for geometry adjustment while refactoring. I added it back in 31a7f30de92ac93240c3fcd7024fcdc38bb9c4ae. Krohnkite will respect (1) resize increment (2) min/max size (3) resizability of window.

> Don't resize windows at all, treat them as if they are resized

This is my current approach. User intention should be respected over soft-limit, as long as doing so causes no critical issues.

**Comment by esjeon** [comment]
The issue has been solved by a series of changes, so I'm closing this.

As a side note:
1. Resize hints are fully respected by Krohnkite. If respecting the hint causes protrusion through screen borders, Krohnkite will relocate such window to keep its whole content on the same screen. This behaviour can be disabled in config, which might yield better experience on single-monitor setup.
2. Non-resizable windows will floated by default, but user still can toggle float on them.
