### ISSUE TITLE
Vertical and horizontal gaps between tiles are not the same

### ISSUE THREAD

**Issue by cxor** [esjeon/krohnkite#26]
Horizontal gap between windows is exactly the half of vertical one. In the [screenshot](https://pasteboard.co/HZFJQqW.png), I set the gap between tiles to be 60px; among tiles 2 and 3 there are 60px, whereas between 1 and 2/3 there are only 30px of space (measured with KRuler).
I know it's a minor issue, but still quite strange visually IMHO.

**Comment by esjeon** [comment]
Thanks for noting out. The issue is fixed by e9bea92.

**Comment by cxor** [comment]
Thank you so much. Kröhnkite rocks!
