### ISSUE TITLE
Resizing non-master window

### ISSUE THREAD

**Issue by Teyras** [esjeon/krohnkite#27]
Do you plan to implement resizing non-master windows in the Tile layout? For example, when I have the master window on the left side and two terminals on the right side, I would sometimes like to make one of those terminals taller.

**Comment by esjeon** [comment]
That's a cool idea, and it's *probably* possible.

FYI, non-master side of the layout is called stack, at least in dwm and likes.

My idea is that I can add a mapping from `Tile` to weight into `TileLayout`. Resizing a window vertically will change its weight based on its new size and the sum of all weights in the stack. The height of the window will be determined from the ratio of weights.

I think this ensures windows to have (rather) persistent sizes, regardless of user actions like minimizing, setting master, and reordering.

**Comment by Teyras** [comment]
What you propose sounds way better than adjusting the sizes of the layout itself, regardless of the actual window placed in that slot. I like it!

**Comment by esjeon** [comment]
It took long enough to clean up the base structure, and now this is finally done. I really like how this is [generalized into a function](https://github.com/esjeon/krohnkite/blob/97b80282e7cebc86fe0385c0091f8e41412476af/src/layouts/layoututils.ts#L87). Please feel free to try this and tell me if anything bothers you.

**Comment by Teyras** [comment]
Wow, awesome! Thanks for implementing this! I'm not sure what bindings I should use to resize the windows on the stack though...

**Comment by aerosol** [comment]
This is amazing @esjeon thank you so much

**Comment by esjeon** [comment]
> I'm not sure what bindings I should use to resize the windows on the stack though...

I've been hesitating to change keybindings, but, yeah, it's about time. (Related: #36)

**Comment by Teyras** [comment]
Agreed. So, is there any way to try out resizing stack windows now?

**Comment by esjeon** [comment]
Oh, you can just resize with your mouse.

**Comment by Teyras** [comment]
I see. I was only trying it with Konsole windows and they didn't want to be resized for some reason. This is really cool, thanks!

**Comment by esjeon** [comment]
Sorry, it took too long, but I finally implemented the resizing feature.

A caveat is that, instead of using 8 keys for resizing all sides in both ways, I decided to stick with 4 keys(<kbd>meta</kbd>+<kbd>ctrl</kbd>+<kbd>h</kbd><kbd>j</kbd><kbd>k</kbd><kbd>l</kbd>), and they resize only **eastern** and **southern** borders. I believe this should be suffice in most cases, and this behaviour can always be overriden per-layout basis for any special cases.

**Comment by esjeon** [comment]
Closing. I think this has been fully accomplished some time ago.
