### ISSUE TITLE
Maximize the window in "Monocle Layout"

### ISSUE THREAD

**Issue by jstarzyk** [esjeon/krohnkite#28]
Thanks for this awesome script!
Is it possible to add an option to automatically maximize the window when "Monocle Layout" is the current layout? Currently the maximize effect only works for the "Tile Layout".

**Comment by esjeon** [comment]
Hmm, the thing is that maximization (of the sole window) works for all layouts, but, indeed, Monocle layout can benefit from the same behaviour, since it always shows only single window at a time. I'll try adding this.

**Comment by jstarzyk** [comment]
Thanks for this. Maximization seems to be working.
