### ISSUE TITLE
Gap incorrectly changes its size

### ISSUE THREAD

**Issue by jstarzyk** [esjeon/krohnkite#29]
**Symptom**
When tiling layout is enabled and there are more than 2 windows in a column, the bottom gap needlessly changes its size.
_Edit_: Left and right gaps are also affected.

**How to Reproduce**
1. Launch more than 2 windows.
2. Arrange them in a column.
3. The bottom (also: left and right) gap between the screen edge and a window increases and decreases its size when adding or minimizing windows.

**Expected behavior**
The gap size should remain constant.

**Environment**
 - Distro: Manjaro
 - KWin version: 5.14.5
 - Krohnkite version: latest commit: 4673135
 - List of KWin scripts in use: MinimizeAll

**Notes**
Video of the bug: https://streamable.com/ytsyz
Another one: https://streamable.com/yra3p

**Comment by esjeon** [comment]
Literally tiny one but good find. It sounds like a floating point rounding error.
