### ISSUE TITLE
Increase/decrease problem

### ISSUE THREAD

**Issue by jstarzyk** [esjeon/krohnkite#30]
**Symptom**
When trying to "decrease" a window, it is sometimes not possible right away. This happens for example after you try to "increase" a window multiple times, but it no longer has an effect on the window.

**How to Reproduce**
1. Launch some windows in tiling mode.
2. Keep "increasing" a window until it has no effect.
3. Try to "increase" the window a few more times (N).
4. Try to "decrease" the window once – not working. You need to "decrease" it N times to observe an effect.

**Expected behavior**
Decreasing windows works instantaneously regardless of the number of previous failed attempts to increase.

**Environment**
 - Distro: Manjaro
 - KWin version: 5.14.5
 - Krohnkite version: latest commit: 4673135
 - List of KWin scripts in use: MinimizeAll

**Notes**
It's working correctly the other way around (decrease multiple times with no effect -> increase only once).

**Comment by esjeon** [comment]
It's actually a feature of `Tile` layout. `Increase` increases the number of master up to 10 (arbitrary limit). It's simply not visible to user, but when you add more windows, they will be arranged accordingly.
