### ISSUE TITLE
[feature request] Auto-minimize on monocle layout

### ISSUE THREAD

**Issue by seqizz** [esjeon/krohnkite#33]
Hi again,

I got used to the plugin and thanks again, working really good :)

One feature request could make the life faster:
Can we put an option under monocle layout which automatically minimizes all windows in the screen except the current one (which is already fullscreen)?
This way we can use "Switch to window ..." keybindings without popping up windows which are not visible.

**Comment by esjeon** [comment]
Thanks for suggesting, and sorry for being late. I don't remember why, but I initially thought this would be tricky (thus couldn't really reply to this), but this seems totally possible now.

**Comment by seqizz** [comment]
Awesome :+1:
I tried to look around the code, since I realized what needs to be done sounds like looping through the clients in workspace on change and minimize all except the current, but phew TS is a hell of a language for me.. :grimacing:

**Comment by seqizz** [comment]
Fyi: Tried nevertheless, currently broken since I couldn't understand what's going on. Posting here if someone wants to dig :octocat: 
https://github.com/esjeon/krohnkite/compare/master...seqizz:g_struggle?expand=1

**Comment by seqizz** [comment]
Tested and working great.
Thanks again for the effort. :tada:
