### ISSUE TITLE
Gaps between tiles (pixels)

### ISSUE THREAD

**Issue by alexjp** [esjeon/krohnkite#34]
Hi,

Using latest git version and with setting "Gaps between tiles (pixels)" to something other than 0, when a single window is opened, creates a gap in the right side of the window ( in the right side of the monitor ).
Opening another window fixes it, ( the gap appears in the middle and not on the sides of the monitor ).

Could this right side empty pixels/gap disappear when only one window ? 

Thanks !

**Comment by esjeon** [comment]
Good find. I haven't realized it lol. I've just fixed it, btw.
