### ISSUE TITLE
Windows opened with latte-dock WM_CLASS are not ignored

### ISSUE THREAD

**Issue by Jimver** [esjeon/krohnkite#37]
**Symptom**
When using [latte-dock](https://github.com/KDE/latte-dock) combined with Krohnkite the opened windows from latte-dock are not ignored, even when included in the ignore window class settings from Krohnkite.

**How to Reproduce**
1. Install and launch latte-dock
2. Add the `latte-dock` WM_CLASS to the ignore window class exceptions and `Latte Settings` to the ignore window title exceptions and reload the script
2. Right click the latte-dock and select Add Widget, then drag `System Tray` onto the latte-dock.
3. Click the network icon in the latte-dock System Tray and you will get a Network window that is not ignored by Krohnkite despite the WM_CLASS being ignored.
![dock network settings](https://user-images.githubusercontent.com/7677699/55095663-d0468d80-50b8-11e9-9858-038b5d8d3e09.png)

**Expected behavior**
The network settings window should be ignored and floating above the other windows.

**Environment**
 - Distro: [e.g. Manjaro KDE Plasma]
 - KWin version: [5.15.3-1]
 - Krohnkite version: [v0.4]
 - List of KWin scripts in use: [MinimizeAll]

**Notes**
The problem is for all windows opened from latte-dock, so battery, sound settings, app launcher etc.

In the Krohnkite settings I have for ignored window classes: 
`krunner,yakuake,spectacle,kded5,latte-dock`
And ignored window titles:
`JetBrains Toolbox,Friends ListString, SharedKey,GLava,Latte Settings`

The output of xprop for the network settings window opened from latte-dock is (I stripped out the ascii_icons for readability):
```
_NET_WM_DESKTOP(CARDINAL) = 0
WM_STATE(WM_STATE):
                window state: Normal
                icon window: 0x0
_KDE_NET_WM_ACTIVITIES(STRING) = "00000000-0000-0000-0000-000000000000"
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_MOVE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_CLOSE
_NET_WM_USER_TIME(CARDINAL) = 1191245
_KDE_NET_WM_SHADOW(CARDINAL) = 54545994, 54546000, 54546001, 54546002, 54546003, 54546004, 54546005, 54546006, 1, 10, 10, 10
_KDE_NET_WM_BLUR_BEHIND_REGION(CARDINAL) = 1, 0, 1532, 686, 2, 686, 1530, 1, 3, 687, 1528, 1
_KDE_SLIDE(_KDE_SLIDE) = 0xffffffff, 0x1
_NET_WM_STATE(ATOM) = _NET_WM_STATE_BELOW, _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_SKIP_PAGER
_KDE_NET_WM_DESKTOP_FILE(UTF8_STRING) = "latte-dock"
XdndAware(ATOM) = BITMAP
WM_NAME(STRING) = 
_NET_WM_NAME(UTF8_STRING) = "Latte Dock"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x1, 0x0, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _KDE_NET_WM_WINDOW_TYPE_OVERRIDE, _NET_WM_WINDOW_TYPE_NORMAL
_XEMBED_INFO(_XEMBED_INFO) = 0x0, 0x1
WM_CLIENT_LEADER(WINDOW): window id # 0x3400012
WM_HINTS(WM_HINTS):
                Client accepts input or input focus: True
                window id # of group leader: 0x3400012
WM_CLIENT_MACHINE(STRING) = "jim-laptop"
_NET_WM_PID(CARDINAL) = 1563
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 54526008
WM_CLASS(STRING) = "latte-dock", "lattedock"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_NORMAL_HINTS(WM_SIZE_HINTS):
                user specified location: 1906, 31
                user specified size: 1534 by 1389
                program specified minimum size: 452 by 398
                program specified maximum size: 3440 by 1409
                window gravity: Static

```

**Comment by Jimver** [comment]
Wow I literally solved it a couple minutes later by adding `Latte Dock` in the ignore window title settings from Krohnkite

**Comment by esjeon** [comment]
> `WM_CLASS(STRING)  = "latte-dock", "lattedock"`

What you see here are (1) resource name and (2) resource class, and Krohnkite matches the latter one. They actually serve different purposes, but maybe I should filter them both.
