### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by SolarAquarion** [esjeon/krohnkite#38]
src/engine/window.ts(54,48): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'Boolean' has no compatible call signatures.
src/engine/window.ts(55,49): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'Boolean' has no compatible call signatures.
make: *** [Makefile:48: pkg/contents/code/script.js] Error 2

**Comment by esjeon** [comment]
That was my stupid mistake. Fixed with 690c71b.
