### ISSUE TITLE
Switching to Monocle layout crashes KWin

### ISSUE THREAD

**Issue by Teyras** [esjeon/krohnkite#39]
**Symptom**
Switching to Monocle layout crashes KWin.

**How to Reproduce**
Open two windows, press meta+m to switch to monocle layout.

**Environment**
 - Distro: Archlinux
 - KWin version: 5.15.4
 - Krohnkite version: 97b8028
 - List of KWin scripts in use: []

**Comment by esjeon** [comment]
Would you provide more details, like applications in use, multi-head setup, etc? I cannot reproduce this on my desktop(nvidia), VM, and testing laptop(intel) that I just setup.

**Comment by Teyras** [comment]
I have a Dell Latitude 5491 with Intel graphics running Arch linux. This happens even on a fresh start with just two instances of Konsole open. Should I look into getting a debug trace?

**Comment by Teyras** [comment]
I'm sorry, this was my mistake - monocle layout removes titlebars, which is a symptom of a KWin crash.

**Comment by esjeon** [comment]
> I'm sorry, this was my mistake - monocle layout removes titlebars, which is a symptom of a KWin crash.

Meh, always thanks for your contribution. I just feel sorry that I'm being somewhat lazy recently.
