### ISSUE TITLE
how to ignore tilix --quake, its role is quake, cannot ignore by class

### ISSUE THREAD

**Issue by zyf0330** [esjeon/krohnkite#42]
**Symptom**
I use tilix quake mode, but cannot ignore it be tiled.

**How to Reproduce**
1. set mode as tile mode
2.  call tilix --quake

**Expected behavior**

**Environment**
 - Distro:  Ubuntu 19.04
 - KWin version: 5.16.1
 - Krohnkite version: [e.g. 0.1, git commit]
 - List of KWin scripts in use: just this

**Notes**

**Comment by esjeon** [comment]
Hmm, weird. Tilix quake mode didn't work when I checked this ticket weeks ago, but it works flawless on my PC today. It seems like either Tilix or KWin made changes that fixed this bug.

I'm just gonna keep this open for a while. If anyone having problems with Tilix quake mode, please feel free to leave comments here.

**Comment by zyf0330** [comment]
So it is ignored by default? I have noticed it too.

**Comment by esjeon** [comment]
You still have to add "tilix" to the ignore list, which you might have done already.

**Comment by zyf0330** [comment]
But I just want to let 'tilix --quake' be ignored, not tilix main window.

Eon S. Jeon <notifications@github.com> 于2019年10月28日周一 下午12:11写道：

**Comment by esjeon** [comment]
Hmm, the only noticeable difference b/w quake mode and normal mode is "window role". I'll implement role-based filtering then.

**Comment by zyf0330** [comment]
Appreciate you!

Eon S. Jeon <notifications@github.com> 于2019年10月28日周一 下午2:48写道：

**Comment by zyf0330** [comment]
Sorry, I have tried newest version, but ignoring role doesnot work for `tilix --quake`.

**Comment by esjeon** [comment]
This had been included in regular releases for a while. Any news here? 'cuz It Works On My PC<sup>TM</sup>

**Comment by zyf0330** [comment]
Thanks, it works!
