### ISSUE TITLE
An option to disable automatically setting 'keep below others' for tiled windows

### ISSUE THREAD

**Issue by ivan-cukic** [esjeon/krohnkite#47]
First of all, thanks for making this. This is the first time I was able to swithch to using the tiling window management full time. Really well done!

The main issue I have with it is that it marks windows as 'keep below'. I understand this is a common behavior for tiling WMs, but I think it would be amazing if this was configurable.

**Comment by esjeon** [comment]
Thanks for the suggestion. I just implemented the option to disable "keep below" on tiled windows.

The purpose of setting "keep below" is to prevent tiled windows from hiding floating windows, but, yeah, why not have another option. It's KDE. I remember myself having problems with this policy in dwm, though my muscle got used to it pretty quickly.

**Comment by ivan-cukic** [comment]
Works like a charm, thanks!

**Comment by OWL4C** [comment]
Hey i know this is an old issue but i don't know if this is working as intended. When in monocle mode, any new window will be stuck in "Keep below others" unless i manually change the setting described here or manually turn of the keep below per window. Is this supposed to be how this works? How would you "raise" a window without using the mouse to toggle of keep below or adding a custom shortcut?
