### ISSUE TITLE
Problem moving windows to other screens

### ISSUE THREAD

**Issue by seqizz** [esjeon/krohnkite#52]
**Symptom**
Hi again,

After upgrading to latest master, I am unable to move windows between screens. It momentarily shows that it's moving and it's bouncing back.

**How to Reproduce**
1. Use latest master
2. Press key for "Window to next (or previous) screen" shortcut (I've set it to Meta+Shift+Right/Left)
3. See the window stays in the screen instead of moving to other screen.

**Expected behavior**
Move window to other screen

**Environment**
 - Distro: Nixos 19.09
 - KWin version: 5.16.5
 - Krohnkite version: 577fc7f55082a6ec0dfc1090c12b79dbb9450398
 - List of KWin scripts in use:
   - Enforces Window Decorations on GTK+ window (< some system installed script, no idea)
   - krohnkite

**Notes**
Installed latest released version (0.5) and issue does not exist.

**Comment by JanMalte** [comment]
Hi @seqizz , I recently found an upstream connection to kwin somewhere. There it was said this is an upstream issue related to: https://bugs.kde.org/show_bug.cgi?id=363804

**Comment by seqizz** [comment]
Hi @JanMalte , thanks for the links. But if these were the case, I assume krohnkite version 0.5 would also not work. (Or am I missing something?)
It's perfectly fine with same system + krohnkite v0.5, but master branch makes it impossible to move windows.

**Comment by JanMalte** [comment]
No, I think you are right. krohnkite v0.5 is working well.

**Comment by esjeon** [comment]
I've just implemented a fix. This, of course, Works on My Computer<sup>TM</sup>, so please feel free to report any problems.

**Comment by alevalv** [comment]
Tested on two machines, the issue is gone, thanks @esjeon !

**Comment by seqizz** [comment]
Sorry couldn't react. Closing, thanks :tada:
