### ISSUE TITLE
[Feature request] Script configuration

### ISSUE THREAD

**Issue by talentlessguy** [esjeon/krohnkite#53]
Currently I can't configure Krohnkite for my needs (I want to blacklist some apps from tiling)

Here's an example GUI settings of another extension

![image](https://user-images.githubusercontent.com/35937217/70389371-b68f7100-19cf-11ea-983d-f49d030f16fc.png)

Would be nice to have something similar

**Comment by esjeon** [comment]
Would you be more specific about your situation? Both Krohnkite 0.5 and master branch supports blacklisting by both window class and title. The only caveat is that you have to follow [a manual step](https://github.com/esjeon/krohnkite/blob/master/README.md#enabling-user-configuration) to enable configuration dialog.

**Comment by talentlessguy** [comment]
oh, didn't see that, closing the issue then
