### ISSUE TITLE
CTRL+I rotates windows to horizontal layout

### ISSUE THREAD

**Issue by snugglej** [esjeon/krohnkite#56]
When I have windows open and then I use CTRL+I (Increase)  it flips the layout from vertical to horizontal (windows stacked on top of each other). 

Is this expected, because I can't seem to get it to revert back to vertical (windows next to each other right to left).

Also if I want to remove a window from one group and add it to the other group how do i do that. Example (3 windows on the left / 1 window on the right --> want to move it to 2 windows on the left / 2 windows on the right) or vice versa.

**Comment by esjeon** [comment]
Oh, I feel a serious need for good documentation here.

> I can't seem to get it to revert back to vertical

Use `Decrease` key, which is supposed to be bound to <kbd>Windows/Meta</kbd> + <kbd>D</kbd>. The thing is, the key is already bound to `Show Desktop`, so you must bind it manually in settings. I'll try changing this to something else.

> I use CTRL+I (Increase) it flips the layout from vertical to horizontal 

The `Increase` hotkey increases the number of so called **master** windows in the layout (though behaviour might differ in some layouts), but, to understand this, you have to understand some basic concepts of tiling WM.

You're probably using `Tile` layout - the default - and, the layout divides the screen into two areas: master & stack. **Master** is the place for important windows, and **stack** is for all the remaining windows. Initially, only one window is put into master, but, with `Increase` and `Decrease` hotkey,  you can adjust the number of windows put into the master area. (Even to zero, effectively creating a vertical layout.)

> if I want to remove a window from one group and add it to the other group how do i do that. 

Krohnkite is modeled after dwm, which prioritizes simplicity as much as possible, so there's no shortcut to move multiple windows from master to stack, at least for the currently available layouts.

But there are three different methods for changing window order:

1. <kbd>Meta</kbd> + <kbd>Shift</kbd> + <kbd>J/K</kbd> to reorder windows one-by-one.
2. <kbd>Meta</kbd> + <kbd>Enter</kbd> to send a window to Master (which is, in fact, just the first window in the list)
3. (Only in git version) Drag a window to another window to *switch* their positions.

**Comment by snugglej** [comment]
Thanks for getting back to me so quick!

I did map the Decrease key and unamped the "Show desktop" option but it didn't change the fact that it wouldn't go back to a vertical stack from the horizontal stack.  Maybe you should map that to `Meta`+`R` for remove from master stack. I'll try changing the mapping right now on my system and see if I can get the "decrease" to work.

`Meta`+`Shift`+`J/K` did not reorder once I was stuck in the vertical stack. But that was because I probably had all the windows in the Master. Since there was nothing in the stack side it couldn't reorder. I'll try the `Meta`+`Enter` to see what happens also.

**Comment by snugglej** [comment]
I switched from CTRL+D to CTRL+R and I was able to switch between master and the stack with the windows. 

Thanks for the quick response and I love the key bindings as they are pretty easy to remember.
