### ISSUE TITLE
Windows Have No Borders

### ISSUE THREAD

**Issue by wildpjah** [esjeon/krohnkite#59]
**Symptom**
New windows are appearing with no borders

**How to Reproduce**
I just installed it and toggle the no border with tiling option to see how it felt, but after turning it off, there are still no borders on any windows not ignored.

**Expected behavior**
I toggle the option off and my windows once again have borders.

**Environment**
 - Distro: Manjaro
 - KWin version: 5.17.5
 - Krohnkite version: 0.6.1
 - List of KWin scripts in use: MinimizeAll

**Notes**
After turning the option off the first couple windows I created did have borders, but after the first 2 or 3 new windows were created without borders, although the first few still had the borders they were originally created with. I have been unable to duplicate this.

**Comment by esjeon** [comment]
I can't reproduce the bug, but the logic needs to be changed anyway.

Krohnkite retains the initial no-border state of windows and reapply it again and again. This change was made to support some applications that touches no-border state, though KWin devs strongly discourage manipulating the state in applications.

However, I think this should be a non-problem if you just restart the session. Or do you have other problems with borders?

**Comment by wildpjah** [comment]
I have this issue no matter how much I restart the session. It seems like it might have to do with creating a new window as after playing around for a while, if I create a new window abnormally such as dragging a new firefox tab to make it a new window, borders are present. But when launching firefox normally there is no border.

**Comment by esjeon** [comment]
Updated the logic. This supports:
 * Windows created w/o border (Chromium)
 * Windows created w/o border, but add it back. (Firefox, Thunderbird. Oh, Mozilla...)
 * Windows created with border, but remove it afterwards. (Chromium)

Another tip is that KWin actually allows toggling window borders with a shortcut, but is unbound by default IIRC.

**Comment by wildpjah** [comment]
Hey that did fix it as far as I can tell
