### ISSUE TITLE
Monitor dependent options

### ISSUE THREAD

**Issue by alexjp** [esjeon/krohnkite#6]
Hi,

So, posting about that "left monitor -> right master and right monitor -> left master" question. Maybe there are set of options that could be handy to be dependent on monitor.

So apart from creating "set master to the right side on left monitor, and master on left side on right monitor", would you think that it could be handy to have different layouts per monitor ? or different gaps size ? ( where one monitor has a panel but the other doesn't ) ?

Thanks ! ( maybe enhancement and brainstorming labels here, maybe I am overcomplicating things here, its not really a major issue)

**Comment by esjeon** [comment]
I'm not sure if it's possible to have the configuration UI to do such thing. `config.ui` is a dumb UI form which is mostly static.

If my understanding is correct, KWin script is a kind of Plasmoid, so it should be able to use QML (`config.qml`, not `config.ui`) for user configuration, but I'm not sure of it yet. All the plasmoids use QML for configuration, yet I can't find an example of KWin script using `config.qml`.

I'm gonna stow this for now.

**Comment by alexjp** [comment]
> I'm gonna stow this for now.

yeah, agree. Adding these options and doing a more advanced config ui would be great, but they are nowhere major.

thanks for the great script !
