### ISSUE TITLE
Resizing tiles affects all desktops

### ISSUE THREAD

**Issue by colorlessean** [esjeon/krohnkite#67]
**Symptom**
When resizing tiles on one workspace it will resize windows on all work spaces.

**How to Reproduce**
1. Open multiple workspaces or desktops.
2. Open at least two tiles on each.
3. Use the Tiling Mode (That's what I have running).
4. Try to resize one of the tiles horizontally or vertically.
5. Go to other desktops and observe it has affected these tiles as well.

**Expected behavior**
Would expect that each desktops tiles would be completely independent so different desktops can have different layouts.

**Environment**
 - Ubuntu 18.04 LTS
 - KWin version: 5.12.9
 - Krohnkite version: 0.7
 - List of KWin scripts in use: Enforce window decorations, Krohnkite

**Notes**
I'm not sure if this is intended or a future improvement already in the pipeline. But I would rather like to have the ability to have unique layouts on each virtual desktop / workspace.

**Comment by esjeon** [comment]
That's the intended "default" behavior. The current default behavior of Krohnkite is to use the same layout for all "surfaces"(activities and desktops). You can change this behavior in the script setting, by checking "Use separate layouts for each Activity/Desktop".

**Comment by colorlessean** [comment]
Works flawlessly, thank you very much I'll look deeper into the menus next time I have some trouble.
