### ISSUE TITLE
Can't build from master

### ISSUE THREAD

**Issue by alxlg** [esjeon/krohnkite#75]
**Symptom**
Can't build from master

**How to Reproduce**
1. `git clone https://github.com/esjeon/krohnkite.git && cd krohnkite`
2. `make install`
3. See error:

```
[...]
tsc
src/layouts/layoututils.ts(41,9): error TS2322: Type 'number[][]' is not assignable to type '[number, number][]'.
  Type 'number[]' is not assignable to type '[number, number]'.
    Property '0' is missing in type 'number[]'.
src/layouts/layoututils.ts(200,15): error TS2322: Type 'number[][]' is not assignable to type '[number, number][]'.
Makefile:71: recipe for target 'krohnkite.js' failed
make: *** [krohnkite.js] Error 2
```

**Environment**
 - Distro: Ubuntu 18.04 / KDE Neon
 - Krohnkite version: master, commit 18e8b62

**Comment by esjeon** [comment]
It seems like a Typescript version issue. Would you tell me which version your `tsc` is?

**Comment by alxlg** [comment]
@esjeon my tsc version is 2.7.2
