### ISSUE TITLE
Applications that start at fullscreen are not tiled

### ISSUE THREAD

**Issue by papadako** [esjeon/krohnkite#76]
If you start an application in fullscreen then the window is not managed by the tile manager and just floats.

**Comment by esjeon** [comment]
Yeah, I can reproduce this with Gwenview. The problem here is that, if a window is created fullscreen from  the very beginning, KWin says it's not resizable, and Krohnkite floats the window. Maybe I can delay the test for those fullscreen windows.

**Comment by esjeon** [comment]
Closing. The fix is applied to v0.8.
