### ISSUE TITLE
Auto Titlebar and border size

### ISSUE THREAD

**Issue by alexjp** [esjeon/krohnkite#8]
Hi,

Thanks for all your work :)

What do you think of the idea of instead of creating a rule for windows not have titlebar, the specific workflow:

* If window is tiling -> remove titlebar and borders ( set to no borders )
* If window is floating -> keep titlebar and borders as configured ( don't change title and borders ).

This makes floating windows look much better and also a very quick distinction between is tiled vs is floating.

Thanks ! :)

**Comment by esjeon** [comment]
I believe that's what `KWin::Client.noBorder` is for. I'll check what it does. 

Also, I think "Remove borders of tiled windows" should be a proper name for this feature.
