### ISSUE TITLE
Floating Layout not working for new windows.

### ISSUE THREAD

**Issue by Thiago4532** [esjeon/krohnkite#80]
I am trying to use Tiling/Floating and I want to toggle tiling option, so I've tried to use Floating Layout but new windows are starting in Tiling mode. Is this normal or it's a bug? Can I disable and enable using shortcuts?

**Comment by esjeon** [comment]
Umm, maybe you are confusing "Float All" feature and "Float Layout"? The former literally floats ALL visible windows, and the latter is the *layout* where every window floats. I just tested both on my computer and both work as intended.

**Comment by Thiago4532** [comment]
It's working when I have two windows at the same desktop, but when I have one this window maximizes. I am uploading the video to show you how it's happening.

**Comment by Thiago4532** [comment]
It was my fault, maximize solo windows was enabled. I am gonna close the issue.
