### ISSUE TITLE
shrink and grow sizes are actually inverted

### ISSUE THREAD

**Issue by formula-spectre** [esjeon/krohnkite#81]
the keyboard shortcut for growing and shrinking the width/height are actually inverted, like control meta L shrinks and H grows the width.

**Comment by esjeon** [comment]
Would you elaborate more? The current behavior is:

1. Resize southern/eastern border. This is to prevent burdening your brain with tons of shortcuts.
2. If the window is the south-most or east-most, northern/western borders are resized instead. This reduces the number of required keystrokes in many cases.

**Comment by formula-spectre** [comment]
i see. window in both sides of the screen behave like i said, on the right and the left. but if it's like you said, i think it's normal. thank you and sorry.

**Comment by esjeon** [comment]
Meh, it was a good point tho. Nothing in README explains how it works anyway.
