### ISSUE TITLE
Manually resizing a window makes it float

### ISSUE THREAD

**Issue by Teyras** [esjeon/krohnkite#9]
I'd expect that resizing a tiled window with the mouse would adjust the layout.

**Comment by esjeon** [comment]
*It's not a bug, It's a feature.* Joke aside, it's really just a remnant from DWM. I think that's a cool feature, but generalization can be difficult.

The solution might be translating window resize by user into a `UserInput`, and let it be processed in `Layout::handleUserInput`. Inside the method, `Layout` can compare the current window size (`KWin::Client.geometry`) to the intended size (`Tile.geometry`), and decide what to do.

The only problem is that "the intended size" isn't always reflected to the actual window size (thanks to window hints, weird policy, etc), and this discrepancy can cause problems. I'll work on this, but it'll be off by default until proven safe.

**Comment by Teyras** [comment]
Thanks for the explanation!

**Comment by esjeon** [comment]
I implemented the feature(6c858735741d839c360b886a0edb09db528364ea) in a generalized way, but only Tile layout supports this currently. I'll try expanding this idea. Maybe I can add some more layouts too.

**Comment by Teyras** [comment]
I love it, thanks for this feature! Also thanks for this script.
