### ISSUE TITLE
Feature Request: when switch focus among windows, show a border for focused window

### ISSUE THREAD

**Issue by zyf0330** [esjeon/krohnkite#92]
When switch focus among windows, it is not clear that which window has be switched to. If can add a UED to alert is great.

**Comment by zyf0330** [comment]
Sorry, I didn't see help about change window border color in README.

**Comment by zyf0330** [comment]
I tried set border color for active window, but it doesn't work in tile or three-columns mode

**Comment by esjeon** [comment]
Actually, Krohnkite has no control over window border color. It's KWin which sets the border color, and it's also up to decorations to use or not use the provided border color.

Also, IIRC, I've seen the same symptom some time ago and restarting session solved it for me.

**Comment by zyf0330** [comment]
Where are settings about kwin border locating? I want to check them.
I just set color according to your README. Maybe it is 0 gap which causes
color cannot be seen?

Eon S. Jeon <notifications@github.com> 于2020年6月18日周四 上午6:56写道：
