### ISSUE TITLE
Suggestion: Seperate Remove Borders And Remove Title Bar

### ISSUE THREAD

**Issue by Trikzon** [esjeon/krohnkite#95]
`Krohnkite Settings -> Options -> Remove borders of tiled windows` makes it so that borders AND title bars are hidden.
I would like to hide my title bar (on titled windows only) but NOT the borders.
This is so I can have a clear indication of which window is active (using the suggestion of colored borders in the README).

I understand I could simply remove title bars by editing the Breeze Window Decoration but it is nice to be able to see the name of the window when it's floating.

**Comment by esjeon** [comment]
Sorry, but this is impossible simply because KWin itself cannot do that. KWin only can toggle on and off the decoration as a whole. Title bars are controlled by each decoration, and there's no API to control them from the outside.
